import type { FlatConfigItem } from "../types.js";

export default [{
  name: "rules/sonar",
  rules: {
    "sonar/anchor-precedence": "error",
    "sonar/argument-type": "error",
    "sonar/arguments-order": "error",
    "sonar/bool-param-default": "error",
    "sonar/class-prototype": "error",
    "sonar/comma-or-logical-or-case": "error",
    "sonar/concise-regex": "error",
    "sonar/cookies": "error",
    "sonar/disabled-auto-escaping": "error",
    "sonar/disabled-resource-integrity": "error",
    "sonar/empty-string-repetition": "error",
    "sonar/function-return-type": "error",
    "sonar/in-operator-type-error": "error",
    "sonar/link-with-target-blank": "error",
    "sonar/misplaced-loop-counter": "error",
    "sonar/new-cap": "error",
    "sonar/no-accessor-field-mismatch": "error",
    "sonar/no-alphabetical-sort": "error",
    "sonar/no-angular-bypass-sanitization": "error",
    "sonar/no-array-delete": "error",
    "sonar/no-associative-arrays": "error",
    "sonar/no-clear-text-protocols": "error",
    "sonar/no-dead-store": "error",
    "sonar/no-empty-after-reluctant": "error",
    "sonar/no-equals-in-for-termination": "error",
    "sonar/no-for-in-iterable": "error",
    // "sonar/no-hardcoded-credentials": "error",
    "sonar/no-hardcoded-ip": "error",
    "sonar/no-in-misuse": "error",
    // "sonar/no-incorrect-string-concat": "error",
    "sonar/no-invalid-await": "error",
    "sonar/no-invariant-returns": "error",
    "sonar/no-misleading-array-reverse": "error",
    "sonar/no-redundant-assignments": "error",
    "sonar/no-try-promise": "error",
    "sonar/no-undefined-argument": "error",
    "sonar/no-useless-intersection": "error",
    "sonar/no-wildcard-import": "error",
    "sonar/non-number-in-arithmetic-expression": "error",
    "sonar/null-dereference": "error",
    "sonar/operation-returning-nan": "error",
    "sonar/post-message": "error",
    "sonar/prefer-promise-shorthand": "error",
    "sonar/prefer-type-guard": "error",
    "sonar/redundant-type-aliases": "error",
    "sonar/stateful-regex": "error",
    "sonar/strings-comparison": "error",
    "sonar/unused-named-groups": "error",
    "sonar/values-not-convertible-to-numbers": "error",
    "sonar/xpath": "error",
  }
}] satisfies FlatConfigItem;
